# Generated by Django 6.0.1 on 2026-04-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_options_lead_assigned_to_lead_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('appointed', 'Appointed'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
